#!/usr/bin/env python3
"""Generate the compact judge page from authoritative committed evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FINAL = ROOT / "proof/r7.5-source-reuse-final-52db138-20260811T1605Z-confirm.json"
TARGETS = ROOT / "proof/r7.5-competition-targets.json"
MATRIX = ROOT / "proof/r7-final-selection-matrix.json"
QUALITY = ROOT / "proof/r7-b2-c1-shared-quality-conditions.json"
PROFILE = ROOT / "proof/r7-final-shared-path-profile-repaired-conditions.json"
CORPUS = ROOT / "proof/m5-validation-corpus.json"
CAMERA = ROOT / "proof/r7-camera-evidence.json"
REVIEW = ROOT / "proof/reviews/R7-R75-HOSTILE-9DAFDBC-20260811.md"
OUTPUT = ROOT / "docs/JUDGE_EVIDENCE.md"


def read(path: Path) -> dict:
    return json.loads(path.read_text())


def render() -> str:
    final = read(FINAL)
    targets = read(TARGETS)
    matrix = read(MATRIX)
    quality = read(QUALITY)
    profile = read(PROFILE)
    corpus = read(CORPUS)
    camera = read(CAMERA)
    review = REVIEW.read_text()

    stats = final["aggregate"]["statistics"]
    quality_final = final["quality"]
    ci = targets["targets"]["T1"]["paired_median_ci_ms"]
    resources = profile["resources"]
    sample_count = len(corpus["samples"])
    real_count = sum(1 for sample in corpus["samples"] if sample.get("kind") == "real")
    procedural_count = sample_count - real_count
    review_status = "SHIP" if "VERDICT: SHIP" in review else "NOT SHIP"

    def ms(value: float) -> str:
        return f"{value:.6f} ms"

    def pct(value: float) -> str:
        return f"{value:.4f}%"

    def scientific(value: float) -> str:
        return f"{value:.7g}".replace("e-0", "e-").replace("e+0", "e+")

    lines = [
        "# PlaneFuse Evidence at a Glance",
        "",
        "> Generated by `scripts/generate_judge_evidence.py`. Numbers below are read from the committed R7.5 confirmation, target evaluation, quality, profiler, corpus, camera, and matrix artifacts; edit those artifacts only through their reproducible checkers.",
        "",
        "## Final reviewed result",
        "",
        f"- B2: **{ms(stats['B2']['p50'])}**",
        f"- C1: **{ms(stats['C1']['p50'])}**",
        f"- C1-SR: **{ms(stats['C1-SR']['p50'])}**",
        f"- C1-SR vs B2: **{pct(final['aggregate']['c1_source_reuse_percentage_vs_b2'])} lower p50**",
        f"- C1-SR vs C1: **{pct(final['aggregate']['c1_source_reuse_percentage_vs_c1'])} lower p50**",
        f"- Paired B2 − C1-SR median 95% CI: **[{ci[0]:.6f}, {ci[1]:.6f}] ms**",
        "",
        "The percentage comparisons are differences between marginal p50 values. The interval is a paired-median bootstrap estimand; they are intentionally not presented as the same statistic.",
        "",
        "## Quality",
        "",
        f"- {sample_count} inputs: {real_count} provenance-bearing real, {procedural_count} deterministic procedural.",
        f"- C1-SR vs C1 top-1 agreement: **{quality_final['c1_source_reuse_top1_agreement']:.1f}**",
        f"- Top-5 set agreement: **{quality_final['c1_source_reuse_top5_set_agreement']:.1f}**",
        f"- Top-5 ranking agreement: **{quality_final['c1_source_reuse_top5_ranking_agreement']:.1f}**",
        f"- Activation maximum absolute error: **{scientific(quality_final['activation_max_absolute_error'])}**",
        "",
        "The independent B2/C1 quality artifact reports the same fixed corpus and retains its historical disagreement details; it is not silently substituted with a smaller smoke corpus.",
        "",
        "## Representation",
        "",
        f"- B2: normalized RGB materialized; {resources['b2_rgb_logical_payload_bytes']:,} B logical / {resources['b2_rgb_metal_allocated_bytes']:,} B Metal allocated.",
        f"- C1-SR: direct transformed native-plane stem; full RGB intermediate **{resources['c1_rgb_logical_payload_bytes']} B**.",
        f"- Both: persistent Float32 activation and **{resources['cpu_element_by_element_activation_copy_bytes']} B** PlaneFuse element-by-element CPU activation copy.",
        f"- Both: same pretrained MobileNetV2 tail with Core ML compute policy `{final['compute_units_policy']}`.",
        "",
        "## Protocol",
        "",
        f"- Five independent Release processes; {final['warmup_triples_per_batch']} warmup triples and {final['measured_triples_per_batch']} measured triples per process.",
        f"- All {len(final['permutations'])} B2/C1/C1-SR permutations, {final['permutation_repeats']} repetitions per permutation/process.",
        "- Fixed 64-input corpus; deterministic 10,000-replicate paired bootstrap.",
        f"- Independent hostile technical review: **{review_status}**, no findings.",
        "",
        "## Important context",
        "",
        "- Pipeline A is faster under its distinct pre-rendered image-input boundary and is contextual, not the matched headline.",
        "- R6.5 direct camera-space fusion was slower and remains a documented negative result.",
        "- T1 passed through R7.5; T2/T3 were not met or established; T4 was not invoked.",
        "- MobileNetV2 is the only claimed pretrained workload on the measured Apple-Silicon environment.",
        "- No universal speedup, power, bandwidth, or deployment claim is made.",
        f"- Stored camera evidence is {camera['status'].replace('_', ' ')}; a fresh camera attempt with zero callbacks produced no inferred live metric.",
        "",
        "## Verify it yourself",
        "",
        "```bash",
        "./pf doctor",
        "./pf setup mobilenetv2",
        "./pf inspect mobilenetv2",
        "./pf verify",
        "./pf bench quick",
        "./pf evidence --check",
        "./scripts/release_validate.sh",
        "```",
        "",
        "Authoritative files: [R7.5 confirmation](../proof/r7.5-source-reuse-final-52db138-20260811T1605Z-confirm.json), [quality](../proof/r7-b2-c1-shared-quality-conditions.json), [profiler](../proof/r7-final-shared-path-profile-repaired-conditions.json), [corpus](../proof/m5-validation-corpus.json), [A/B/C matrix](../proof/r7-final-selection-matrix.json), and [independent review](../proof/reviews/R7-R75-HOSTILE-9DAFDBC-20260811.md).",
        "",
        f"Evidence generator inputs: `{matrix['strongest_credible_matched_b']}` is the strongest credible matched B; `{matrix['strongest_accepted_stable_c']}` is the strongest pre-R7.5 stable C. The final headline is the source-reuse variant recorded in the R7.5 confirmation.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write docs/JUDGE_EVIDENCE.md")
    parser.add_argument("--check", action="store_true", help="fail if the committed page is stale")
    parser.add_argument("--print", dest="print_output", action="store_true", help="print the generated page")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print(f"FAIL judge evidence: {OUTPUT} is stale; run ./pf evidence")
            return 1
        print("PASS judge evidence: generated page matches authoritative artifacts")
        return 0
    if args.write or not OUTPUT.exists():
        OUTPUT.write_text(generated)
        print(f"PASS judge evidence: wrote {OUTPUT.relative_to(ROOT)}")
    if args.print_output:
        print(generated, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
